/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "network_mngr.h"


void
network_mngr_prog_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	char *user_logins_1_arg;
	char * *result_2;
	long  date_1_arg;
	double  *result_3;
	char *cpu_usage_1_arg;
	double  *result_4;
	char *mem_usage_1_arg;
	double  *result_5;
	char *load_procs_per_min_1_arg;
	system_statistics  *result_6;
	char *get_current_system_stats_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, NETWORK_MNGR_PROG, NETWORK_MNGR, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = user_logins_1((void*)&user_logins_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = date_1(&date_1_arg, clnt);
	if (result_2 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = cpu_usage_1((void*)&cpu_usage_1_arg, clnt);
	if (result_3 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = mem_usage_1((void*)&mem_usage_1_arg, clnt);
	if (result_4 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = load_procs_per_min_1((void*)&load_procs_per_min_1_arg, clnt);
	if (result_5 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = get_current_system_stats_1((void*)&get_current_system_stats_1_arg, clnt);
	if (result_6 == (system_statistics *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	network_mngr_prog_1 (host);
exit (0);
}
