/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NETWORK_MNGR_H_RPCGEN
#define _NETWORK_MNGR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define NETWORK_MNGR_PROG 0x31234567
#define NETWORK_MNGR 1

#if defined(__STDC__) || defined(__cplusplus)
#define DATE 1
extern  char ** date_1(long *, CLIENT *);
extern  char ** date_1_svc(long *, struct svc_req *);
#define CPU_USAGE 2
extern  double * cpu_usage_1(void *, CLIENT *);
extern  double * cpu_usage_1_svc(void *, struct svc_req *);
#define MEM_USAGE 3
extern  double * mem_usage_1(void *, CLIENT *);
extern  double * mem_usage_1_svc(void *, struct svc_req *);
#define LOAD_PROCS_PER_MIN 4
extern  double * load_procs_per_min_1(void *, CLIENT *);
extern  double * load_procs_per_min_1_svc(void *, struct svc_req *);
#define USER_LOGINS 5
extern  char ** user_logins_1(void *, CLIENT *);
extern  char ** user_logins_1_svc(void *, struct svc_req *);
extern int network_mngr_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DATE 1
extern  char ** date_1();
extern  char ** date_1_svc();
#define CPU_USAGE 2
extern  double * cpu_usage_1();
extern  double * cpu_usage_1_svc();
#define MEM_USAGE 3
extern  double * mem_usage_1();
extern  double * mem_usage_1_svc();
#define LOAD_PROCS_PER_MIN 4
extern  double * load_procs_per_min_1();
extern  double * load_procs_per_min_1_svc();
#define USER_LOGINS 5
extern  char ** user_logins_1();
extern  char ** user_logins_1_svc();
extern int network_mngr_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NETWORK_MNGR_H_RPCGEN */
