/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "network_mngr.h"

bool_t
xdr_system_statistics (XDR *xdrs, system_statistics *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->date, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->cpu_usage, sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->mem_usage, sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->load_procs_per_min, sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}
