/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <time.h>
#include <stdio.h>
#include <unistd.h>
#include <sys/sysinfo.h>
#include <pwd.h>
#include <string.h>
#include <utmp.h>


#define MAX_LEN 100

typedef struct {
    char userNames;
    int num;
} User;

User *
cpu_usage()
{
    static char **result;
    int total = 0;

    result = malloc(total * sizeof(char *));

    struct utmp *data;
    data = getutent();
    int i = 0 ;
    while(data != NULL)
    {
            int length = strlen(data->ut_user);
            result[i] = malloc(length * sizeof(char));
            strcpy(result[i], data->ut_user);
            i++;
            data = getutent();
    }

    int size = sizeof(result) + sizeof(i);

    User* userResult = malloc(size);
    userResult->num = i;
    userResult->userNames = result;

  return userResult;
}

int
main (int argc, char *argv[])
{
	User* result;

    result = cpu_usage();
    char **results = malloc(sizeof(result->userNames));
    results = result->userNames;

    for(int i = 0; i < result-> num; i++){
        printf("%s", results[i]);
    }

    printf("%d", result->num);

exit (0);
}
