/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "network_mngr.h"
#include <time.h>
#include <stdio.h>
#include <unistd.h>
#include <sys/sysinfo.h>
#include <pwd.h>
#include <string.h>
#include <utmp.h>

char ** returnUserNames(){
    static char *result;
    int total = 0;

    result = malloc(total * sizeof(char *));

    struct utmp *data;
    data = getutent();
    int i = 0 ;
    while(data != NULL)
    {
            int length = strlen(data->ut_user);
            realloc(result, (length * sizeof(char)) + sizeof(result));
            strncat(result, data->ut_user, length);
            i++;
            data = getutent();
    }

    return &result;
}

int
main (int argc, char *argv[])
{
	static char **result;
    int i = 0;

    result = returnUserNames();

    printf("size %s", *result);

exit (0);
}
