/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "network_mngr.h"
#include <time.h>
#include <stdio.h>
#include <unistd.h>
#include <sys/sysinfo.h>
#include <pwd.h>
#include <string.h>
#include <utmp.h>

char ** returnUserNames(){
    static char *result;
    int total = 0;

    result = malloc(total * sizeof(char *));

    struct utmp *data;
    data = getutent();
    while(data != NULL)
    {
            char * line;
            asprintf(&line, "Username: %s\n", data->ut_user);
            asprintf(&result, "%s%s", result, line);
            data = getutent();
    }

    return &result;
}

int
main (int argc, char *argv[])
{
	static char **result;
    int i = 0;

    result = returnUserNames();

    printf("%s", *result);

exit (0);
}
